spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/gunsCafe
    username: sa
    password: 12345
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create #생성될때마다 초기화, ↔ NONE
    properties:
      hibernate:
        format_sql: true
        show_sql : true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  logging:
    level:
      org.hibernate.SQL: debug
